### ISSUE TITLE
where is the requirements.txt? I don't find it anywhere.

### ISSUE THREAD

**Issue by RandomTuringDuck** [avinsit123/keyphrase-gan#3]
where is the requirements.txt? I don't find it anywhere.

**Comment by RandomTuringDuck** [comment]
The code has too many bugs and it doesn't work.

**Comment by avinsit123** [comment]
I have transferred the codes from a local server to github so there might be some issue with remaining files. Pls list all the parts where you are facing problems . I will try to fix them.

**Comment by RandomTuringDuck** [comment]
> I have transferred the codes from a local server to github so there might be some issue with remaining files. Pls list all the parts where you are facing problems . I will try to fix them.

I have resolved these problems. I get the requirments.txt from "keyphrase-generation-rl". 
Now I can run it, so let's see the effect of this model. Thanks.

**Comment by SaidaSaad** [comment]
@RandomTuringDuck hello, did you able to run the code?
